# Generated by Django 3.0.7 on 2020-06-22 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0003_shopitems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopItems',
        ),
    ]
