# Generated by Django 3.0.7 on 2020-06-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0004_delete_shopitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('buyer', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('shoplists', models.ManyToManyField(to='piano.ShopList')),
                ('users', models.ManyToManyField(to='piano.Users')),
            ],
        ),
    ]
