# Generated by Django 3.0.7 on 2020-06-23 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0006_place_restaurant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['name', 'address']},
        ),
    ]
