# Generated by Django 3.0.7 on 2020-06-23 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0008_auto_20200623_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreview',
            name='article_ptr',
        ),
        migrations.RemoveField(
            model_name='bookreview',
            name='book_ptr',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookReview',
        ),
    ]
