# Generated by Django 3.0.7 on 2020-06-23 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0010_article_book_bookreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('shoplist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piano.ShopList')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piano.Users')),
            ],
        ),
        migrations.RemoveField(
            model_name='bookreview',
            name='article_ptr',
        ),
        migrations.RemoveField(
            model_name='bookreview',
            name='book_ptr',
        ),
        migrations.RemoveField(
            model_name='shopitems',
            name='shoplists',
        ),
        migrations.RemoveField(
            model_name='shopitems',
            name='users',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookReview',
        ),
        migrations.DeleteModel(
            name='ShopItems',
        ),
        migrations.AddField(
            model_name='shoplist',
            name='users',
            field=models.ManyToManyField(through='piano.UserShopItem', to='piano.Users'),
        ),
    ]
