# Generated by Django 3.0.7 on 2020-06-24 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0011_auto_20200623_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discuss_type', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=10000)),
                ('time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piano.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('discuss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piano.Discuss')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piano.Users')),
            ],
        ),
    ]
