# Generated by Django 3.0.7 on 2020-07-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0012_comments_discuss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discuss',
            name='discuss_type',
            field=models.CharField(max_length=255),
        ),
    ]
